(* open Core *)

(* module StaticsError = struct *)
(*   type t = *)
(*     | TypVar of Var.Typ_var.t *)
(*     | ExpVar of Var.Exp_var.t *)
(*     | Type of string * unit Typ.t *)
(*     | MissingLabel of string * Label.t *)
(*     | Elim of string * Var.Exp_var.t * unit Typ.t *)
(*     | Prim of Prim.t * unit Typ.t *)
(*   [@@deriving sexp] *)

(*   let to_string (_err : t) = failwith "todo" *)
(*   (\* let empty = Typ.Map.empty in *)
(*     String.concat *)
(*     @@ *)
(*     match err with *)
(*     | TypVar t -> [ "unbound type variable "; Var.Typ_var.to_string t ] *)
(*     | ExpVar v -> [ "unbound expression variable "; Var.Exp_var.to_string v ] *)
(*     | Type (s, typ) -> [ "incorrect type, expected a "; s; " type but got "; Typ.to_string empty typ ] *)
(*     | MissingLabel (f, l) -> [ "missing label "; Label.to_string l; " in "; f ] *)
(*     | Elim (s, exp, typ) -> *)
(*         [ "attempted to use elim form "; s; " on "; Exp.to_string empty exp; " : "; Typ.to_string empty typ ] *)
(*     | Check (exp, typ1, typ2) -> *)
(*         [ "expected "; Exp.to_string empty exp; " : "; Typ.to_string empty typ1; ", got "; Typ.to_string empty typ2 ] *)
(*     | Prim (op, typ) -> *)
(*         [ *)
(*           "primitive operator "; *)
(*           Sexp.to_string (Exp.sexp_of_prim op); *)
(*           " cannot accept args of types "; *)
(*           Typ.to_string empty typ; *)
(*         ] *\) *)
(* end *)

(* exception TypeError of StaticsError.t *)

(* let validateType typ = if not (Set.is_empty (Typ.frees typ)) then failwith "unbound type variable" *)
(* (\* raise @@ TypeError (StaticsError.TypVar t) *\) *)

(* open Raml *)

(* type ctx = { metactx : (unit Typ.t list * unit Typ.t) String.Map.t; varctx : unit Typ.t Var.Map.t; target : unit Typ.t } *)

(* let check { exnType; decls; _ } = *)
(*   let lookup ctx v = match Map.find ctx v with None -> raise @@ TypeError (StaticsError.ExpVar v) | Some tau -> tau in *)
(*   let rec checkExp (ctx : ctx) (e : Exp.t) : unit = *)
(*     match Exp.out e with *)
(*     | Eret v -> checkVal ctx v *)
(*     | Eapp { func; arg } -> begin *)
(*         match Typ.out (lookup ctx.varctx func) with *)
(*         | Tarr { argty; resty; _ } -> *)
(*             if Typ.(resty <> ctx.target) then raise (TypeError (Type ("Vvar", ctx.target))); *)
(*             checkVal { ctx with target = argty } arg *)
(*         | _ -> failwith "malformed" *)
(*       end *)
(*     | Emetaapp { metafunc; args } -> begin *)
(*         let arg_types, result_type = Map.find_exn ctx.metactx metafunc in *)
(*         if Typ.(result_type <> ctx.target) then raise (TypeError (Type ("Vvar", ctx.target))); *)
(*         List.iter2_exn args arg_types ~f:(fun arg target -> checkVal { ctx with target } arg) *)
(*       end *)
(*     | Ecasefold { arg; unfolded; body } -> begin *)
(*         let argty = lookup ctx.varctx arg in *)
(*         match Typ.out argty with *)
(*         | Trec { self; ty; _ } -> *)
(*             let varctx = Map.set ctx.varctx ~key:unfolded ~data:(Typ.subst argty self ty) in *)
(*             checkExp { ctx with varctx } body *)
(*         | _ -> failwith "malformed" *)
(*       end *)
(*     | Ecase { arg; cases } -> begin *)
(*         match Typ.out (lookup ctx.varctx arg) with *)
(*         | Tsum { ts; _ } -> *)
(*             let f ~key:_ ~data = *)
(*               match data with *)
(*               | `Both (lt, (v, e)) -> *)
(*                   let varctx = Map.set ctx.varctx ~key:v ~data:lt in *)
(*                   checkExp { ctx with varctx } e *)
(*               | _ -> failwith "malformed" *)
(*             in *)
(*             Map.iter2 ts cases ~f *)
(*         | _ -> failwith "malformed" *)
(*       end *)
(*     | Esplit { arg; entries; body } -> begin *)
(*         match Typ.out (lookup ctx.varctx arg) with *)
(*         | Tprod ts -> *)
(*             let f ~key:_ ~data ctx = *)
(*               match data with `Both (x, t) -> Map.set ctx ~key:x ~data:t | _ -> failwith "malformed" *)
(*             in *)
(*             let varctx = Map.fold2 entries ts ~init:ctx.varctx ~f in *)
(*             checkExp { ctx with varctx } body *)
(*         | _ -> failwith "malformed" *)
(*       end *)
(*     | Etick { cont; _ } -> checkExp ctx cont *)
(*     | Eprimapp { prim; args } -> begin *)
(*         let argtypes = *)
(*           let f arg = *)
(*             match Value.out arg with *)
(*             | Vvar arg -> lookup ctx.varctx arg *)
(*             | Vconst (Vint _) -> Typ.base Bint *)
(*             | Vconst (Vfloat _) -> Typ.base Bfloat *)
(*             | Vconst (Vstring _) -> Typ.base Bstring *)
(*             | _ -> failwith "malformed" *)
(*           in *)
(*           List.map args ~f *)
(*         in *)
(*         let result_type = *)
(*           let open Typ in *)
(*           match (prim, List.map argtypes ~f:Typ.out) with *)
(*           | Neg, [ Tbase Bint ] -> Typ.base Bint *)
(*           | Neg, [ Tbase Bfloat ] -> Typ.base Bfloat *)
(*           | Sqrt, [ Tbase Bfloat ] -> Typ.base Bfloat *)
(*           | Plus, [ Tbase Bint; Tbase Bint ] -> Typ.base Bint *)
(*           | Plus, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.base Bfloat *)
(*           | Minus, [ Tbase Bint; Tbase Bint ] -> Typ.base Bint *)
(*           | Minus, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.base Bfloat *)
(*           | Times, [ Tbase Bint; Tbase Bint ] -> Typ.base Bint *)
(*           | Times, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.base Bfloat *)
(*           | Div, [ Tbase Bint; Tbase Bint ] -> Typ.base Bint *)
(*           | Div, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.base Bfloat *)
(*           | Mod, [ Tbase Bint; Tbase Bint ] -> Typ.base Bint *)
(*           | Mod, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.base Bfloat *)
(*           | Lt, [ Tbase Bint; Tbase Bint ] -> Typ.bool *)
(*           | Lt, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.bool *)
(*           | Lte, [ Tbase Bint; Tbase Bint ] -> Typ.bool *)
(*           | Lte, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.bool *)
(*           | Gt, [ Tbase Bint; Tbase Bint ] -> Typ.bool *)
(*           | Gt, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.bool *)
(*           | Gte, [ Tbase Bint; Tbase Bint ] -> Typ.bool *)
(*           | Gte, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.bool *)
(*           | Eq, [ Tbase Bint; Tbase Bint ] -> Typ.bool *)
(*           | Eq, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.bool *)
(*           | Eq, [ Tbase Bstring; Tbase Bstring ] -> Typ.bool *)
(*           | Neq, [ Tbase Bint; Tbase Bint ] -> Typ.bool *)
(*           | Neq, [ Tbase Bfloat; Tbase Bfloat ] -> Typ.bool *)
(*           | Neq, [ Tbase Bstring; Tbase Bstring ] -> Typ.bool *)
(*           | Append, [ Tbase Bstring; Tbase Bstring ] -> Typ.base Bstring *)
(*           | _ -> failwith "malformed" *)
(*         in *)
(*         if Typ.(result_type <> ctx.target) then raise (TypeError (Type ("Vvar", ctx.target))) *)
(*       end *)
(*     | Eraise arg -> checkVal { ctx with target = exnType } arg *)
(*     | Eseq { e; etyp; handler; return } -> *)
(*         checkExp { ctx with target = etyp } e; *)
(*         let check1 ty (x, e) = *)
(*           let varctx = Map.set ctx.varctx ~key:x ~data:ty in *)
(*           checkExp { ctx with varctx } e *)
(*         in *)
(*         Option.iter handler ~f:(check1 exnType); *)
(*         Option.iter return ~f:(check1 etyp) *)
(*   and checkVal (ctx : ctx) (v : Value.t) : unit = *)
(*     match (Value.out v, Typ.out ctx.target) with *)
(*     | Vvar x, _ -> if Typ.(lookup ctx.varctx x <> ctx.target) then raise (TypeError (Type ("Vvar", ctx.target))) *)
(*     | Vconst (Vint _), Tbase Bint -> () *)
(*     | Vconst (Vfloat _), Tbase Bfloat -> () *)
(*     | Vconst (Vstring _), Tbase Bstring -> () *)
(*     | Vlam { argv; body }, Tarr { argty; resty; _ } -> *)
(*         let varctx = Map.set ctx.varctx ~key:argv ~data:argty in *)
(*         checkExp { ctx with varctx; target = resty } body *)
(*     | Vfold arg, Trec { self; ty; _ } -> checkVal { ctx with target = Typ.subst ctx.target self ty } arg *)
(*     | Vinj { con; arg }, Tsum { ts; _ } -> checkVal { ctx with target = Map.find_exn ts con } arg *)
(*     | Vprod vs, Tprod ts -> *)
(*         let f ~key ~data = *)
(*           match data with *)
(*           | `Both (v, target) -> checkVal { ctx with target } v *)
(*           | _ -> raise (TypeError (MissingLabel ("Vprod", key))) *)
(*         in *)
(*         Map.iter2 vs ts ~f *)
(*     | _ -> failwith "wrong type" *)
(*   in *)
(*   let checkFuncs (metactx : (unit Typ.t list * unit Typ.t) String.Map.t) (d : Raml.decl) : *)
(*       (unit Typ.t list * unit Typ.t) String.Map.t = *)
(*     match d with *)
(*     | Funs fs -> *)
(*         let metactx = *)
(*           let f acc func = *)
(*             let MetaFunc.{ func; args; result; _ } = MetaFunc.out func in *)
(*             let _, argtys = List.unzip args in *)
(*             Map.set acc ~key:func ~data:(argtys, result) *)
(*           in *)
(*           List.fold fs ~init:metactx ~f *)
(*         in *)
(*         let f func = *)
(*           let MetaFunc.{ args; result; body; _ } = MetaFunc.out func in *)
(*           let varctx = Var.Map.of_alist_exn args in *)
(*           checkExp { metactx; varctx; target = result } body *)
(*         in *)
(*         List.iter fs ~f; *)
(*         metactx *)
(*     | Config _ -> metactx *)
(*   in *)
(*   let _ = List.fold decls ~init:String.Map.empty ~f:checkFuncs in *)
(*   () *)
